name: Hello World

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Build image
        with:
          dockerfile: Dockerfile
          tags: latest
